version: "3.9"

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: $DATABASE_MIGRATION_USERNAME
      POSTGRES_PASSWORD: $DATABASE_MIGRATION_PASSWORD
      POSTGRES_DB: $DATABASE_NAME

  postgres-migrator:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./migrations:/home/app/migrations
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_PORT: 5432
      DATABASE_MIGRATION_USERNAME: $DATABASE_MIGRATION_USERNAME
      DATABASE_MIGRATION_PASSWORD: $DATABASE_MIGRATION_PASSWORD
      DATABASE_APP_PASSWORD: $DATABASE_APP_PASSWORD

volumes:
  postgres-data:

